config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'mouses#index'
  resources :mouses, only: [:index, :show] do
    collection do
      get 'search'
    end
  end
  resources :reviews, only: [:create, :destroy]

  namespace :admin do
    resources :mouse, only: [:new, :create, :edit, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection < ActiveHash::Base
  self.data = [
    {id: 1, name: '---'},
    {id: 2, name: '無線'},
    {id: 3, name: '有線'}
  ]

  include ActiveHash::Associations
  has_many :mouses
end

app/models/grip_type.rb
class GripType < ActiveHash::Base
  self.data = [
    {id: 1, name: '---'},
    {id: 2, name: 'つまみ持ち'},
    {id: 3, name: '掴み持ち'},
    {id: 4, name: '掴みかぶせ持ち'},
    {id: 5, name: 'かぶせ持ち'}
  ]

  include ActiveHash::Associations
  has_many :reviews
end

app/models/maker.rb
class Maker < ActiveHash::Base
  self.data = [
    {id: 1, name: '---'},
    {id: 2, name: 'ASUS'},
    {id: 3, name: 'BenQ'},
    {id: 4, name: 'Corsair'},
    {id: 5, name: 'Dell'},
    {id: 6, name: 'Endgame Gear'},
    {id: 7, name: 'Final Mouse'},
    {id: 8, name: 'Fnatic Gear'},
    {id: 9, name: 'Glorious'},
    {id: 10, name: 'HyperX'},
    {id: 11, name: 'Logicool'},
    {id: 12, name: 'MSI'},
    {id: 13, name: 'Pulsar'},
    {id: 14, name: 'Razer'},
    {id: 15, name: 'Steel Series'},
    {id: 16, name: 'Vaxee'},
    {id: 17, name: 'Xtrfy'},
    {id: 18, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :mouses
end

app/models/mouse.rb
class Mouse < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :maker
  belongs_to :connection
  belongs_to :symmetry
  belongs_to :software
  has_one_attached :image
  
  belongs_to :user
  has_many :reviews, dependent: :destroy

  with_options presence: true do
    validates :name
    validates :weight
    validates :dpi
    validates :order_url
  end

  with_options presence: true,  numericality: {other_than: 1, message: "can't be blank"} do
    validates :maker_id
    validates :connection_id
    validates :symmetry_id
    validates :software_id
  end
end

app/models/mouse_mid.rb
class MouseMid
  include ActiveModel::Model
  attr_accessor :grip_type_id, :play_game_id, :rating, :usability, :user_id, :mouse_id, :review_id

  #reviewモデルのバリデーション
  
  #review_mouseモデルのバリデーション
  validates :mouse_id, presence: true

  def save
    review_mouse = Review.create(grip_type_id: grip_type_id, play_game_id: play_game_id, rating: rating, usability: usability, user_id: user_id)
    ReviewMouse.create(mouse_id: mouse_id, review_id: review_mouse.id)
  end
end

app/models/play_game.rb
class PlayGame < ActiveHash::Base
  self.data = [
    {id: 1, name: '---'},
    {id: 2, name: 'Apex Legends'},
    {id: 3, name: 'Over Watch'},
    {id: 4, name: 'Valorant'},
    {id: 5, name: 'PUBG'},
    {id: 6, name: 'Counter Strike'},
    {id: 7, name: 'Rainbow 6:siege'}
  ]

  include ActiveHash::Associations
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :grip_type
  belongs_to :play_game
  
  belongs_to :user
  belongs_to :mouse

  with_options presence: true, numericality: { other_than: 1, message: "can't be blank"} do
    validates :grip_type_id
    validates :play_game_id
  end

  with_options presence: true do
    validates :rating, format: { with: /\A[1-5]\z/, message: "is invalid. Input number from 1 to 5 in half-width.", allow_blank: true }
    validates :usability
  end
end

app/models/software.rb
class Software < ActiveHash::Base
  self.data = [
    {id: 1, name: '---'},
    {id: 2, name: '有り'},
    {id: 3, name: '無し'}
  ]

  include ActiveHash::Associations
  has_many :mouses
end

app/models/symmetry.rb
class Symmetry < ActiveHash::Base
  self.data = [
    {id: 1, name: '---'},
    {id: 2, name: '左右対称'},
    {id: 3, name: '左右非対称'}
  ]

  include ActiveHash::Associations
  has_many :mouses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :mice
  has_many :reviews

  with_options presence: true do
    validates :nickname
    validates :password, format: {with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: "is invalid. Input half-width characters.", allow_blank: true}
  end

  validates :admin, exclusion: {in: [true], message: "is invalid value entered"}

end

app/controllers/admin/mouse_controller.rb
class Admin::MouseController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :if_not_admin

  def new
    @mouse = Mouse.new
  end

  def create
    @mouse = Mouse.new(mouse_params)
    if @mouse.valid?
      @mouse.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @mouse = Mouse.find(params[:id])
  end

  def update
    @mouse = Mouse.find(params[:id])
    if @mouse.update(mouse_params)
      redirect_to mouse_path(@mouse.id)
    else
      render :edit
    end
  end

  def destroy
    mouse = Mouse.find(params[:id])
    if current_user.id == mouse.user_id
      mouse.destroy
      redirect_to root_path
    else
      render template: "mouses/index"
    end
  end

  private
  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end

  def mouse_params
    params.require(:mouse).permit(:name, :maker_id, :connection_id, :symmetry_id, :weight, :dpi, :software_id, :software_url, :order_url, :image).merge(user_id: current_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :hand_size])
  end

end

app/controllers/mouses_controller.rb
class MousesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @mice = Mouse.includes(:user).order("created_at DESC")
  end
  
  def show
    @mouse = Mouse.find(params[:id])
    @reviews = @mouse.reviews.includes(:mouse).order("created_at DESC")
    @review = Review.new
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :if_admin

  def create
    @review = Review.new(review_params)
    @mouse = Mouse.find(@review.mouse_id)
    if @review.valid?
      @review.save
      redirect_to mouse_path(@mouse.id)
    else
      render template: "mouses/show"
    end
  end
  
  def destroy
    review = Review.find(params[:id])
    if current_user.id == review.user_id
      review.destroy
      redirect_to mouse_path(params[:mouse_id])
    else
      render template: "mouses/show"
    end
  end

  private
  def review_params
    params.require(:review).permit(:grip_type_id, :play_game_id, :rating, :usability, :mouse_id).merge(user_id: current_user.id)
  end

  def if_admin
    redirect_to root_path if current_user.admin?
  end
end

app/helpers/admin/mouse_helper.rb
module Admin::MouseHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mouses_helper.rb
module MousesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/mouse/edit.html.erb
<%= render 'share/header' %>

<h1>マウスを編集するページです</h1>

<h2> マウスの編集フォーム</h2>
<div class="mouse-form"> 
  <%= form_with model: @mouse, url: admin_mouse_path(@mouse.id), local: true do |f|%>

  <%= render 'share/error_messages', model: @mouse, collection: @messages %>

  <div class="img-upload">
      <div class="weight-bold-text">
        マウス画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"mouse-image" %>
      </div>
  </div>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        マウスの名前
        <span class="require-text">必須</span>
      </div>
  </div>
  <%= f.text_area :name, class:"mouse-name", placeholder:"マウスの名前", maxlength:"40" %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        メーカー
        <span class="require-text">必須</span>
      </div>
  </div>
  <%= f.collection_select(:maker_id, Maker.all, :id, :name, {}, {class:"mouse-maker"}) %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        接続方式
        <span class="require-text">必須</span>
      </div>
  </div>
  <%= f.collection_select(:connection_id, Connection.all, :id, :name, {}, {class:"mouse-connection"}) %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        対称性
        <span class="require-text">必須</span>
      </div>
  </div>
  <%= f.collection_select(:symmetry_id, Symmetry.all, :id, :name, {}, {class:"mouse-symmetry"}) %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        重さ
        <span class="require-text">必須</span>
      </div>
  </div>
  <%= f.text_area :weight, placeholder:"マウスの重さ", class:"mouse-size" %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        dpi
        <span class="require-text">必須</span>
      </div>
  </div>
  <%= f.text_area :dpi, placeholder:"dpiの設定範囲", class:"mouse-dpi" %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        設定ドライバーの有無
        <span class="require-text">必須</span>
      </div>
  </div>
  <%= f.collection_select(:software_id, Software.all, :id, :name, {}, {class:"mouse-software-id"}) %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        設定ドライバーのURL
        <span class="require-text">任意</span>
      </div>
  </div>
  <%= f.text_area :software_url, placeholder:"ドライバーのURL", class:"mouse-software-url" %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        購入サイトのURL
        <span class="require-text">任意</span>
      </div>
  </div>
  <%= f.text_area :order_url, placeholder:"購入サイトのURL", class:"mouse-order-url" %>

  <div class="">
      <div class="weight-bold-text">
      </div>
    <%= f.submit '変更する', class: "change-btn"%>
    <%= link_to '戻る', mouse_path(@mouse.id), class:"return-btn"%>
  </div>
  <% end %>
</div>

app/views/admin/mouse/new.html.erb
<%= render 'share/header' %>

<h1>マウスを投稿するページです</h1>

<h2> マウスの投稿フォーム</h2>
<div class="mouse-form"> 
  <%= form_with model: @mouse, url: admin_mouse_index_path, local: true do |f|%>

  <%= render 'share/error_messages', model: @mouse, collection: @messages %>

  <div class="img-upload">
      <div class="weight-bold-text">
        マウス画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"mouse-image" %>
      </div>
  </div>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        マウスの名前
        <span class="require-text">必須</span>
      </div>
  </div>
  <%= f.text_area :name, class:"mouse-name", placeholder:"マウスの名前", maxlength:"40" %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        メーカー
        <span class="require-text">必須</span>
      </div>
  </div>
  <%= f.collection_select(:maker_id, Maker.all, :id, :name, {}, {class:"mouse-maker"}) %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        接続方式
        <span class="require-text">必須</span>
      </div>
  </div>
  <%= f.collection_select(:connection_id, Connection.all, :id, :name, {}, {class:"mouse-connection"}) %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        対称性
        <span class="require-text">必須</span>
      </div>
  </div>
  <%= f.collection_select(:symmetry_id, Symmetry.all, :id, :name, {}, {class:"mouse-symmetry"}) %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        重さ
        <span class="require-text">必須</span>
      </div>
  </div>
  <%= f.text_area :weight, placeholder:"マウスの重さ", class:"mouse-size" %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        dpi
        <span class="require-text">必須</span>
      </div>
  </div>
  <%= f.text_area :dpi, placeholder:"dpiの設定範囲", class:"mouse-dpi" %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        設定ドライバーの有無
        <span class="require-text">必須</span>
      </div>
  </div>
  <%= f.collection_select(:software_id, Software.all, :id, :name, {}, {class:"mouse-software-id"}) %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        設定ドライバーのURL
        <span class="require-text">任意</span>
      </div>
  </div>
  <%= f.text_area :software_url, placeholder:"ドライバーのURL", class:"mouse-software-url" %>

  <div class="mouse-summery">
      <div class="weight-bold-text">
        購入サイトのURL
        <span class="require-text">任意</span>
      </div>
  </div>
  <%= f.text_area :order_url, placeholder:"購入サイトのURL", class:"mouse-order-url" %>

  <div class="">
      <div class="weight-bold-text">
      </div>
    <%= f.submit '投稿する' %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MouseReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mouses/index.html.erb
<%= render 'share/header' %>

<div class="index-main-image">
  <%= image_tag 'Top-page.png', class:"top-image"%>
  <p class="catch-copy"><b>Aim With Devise</b></p>
  <p class="catch-copy-sub"><b>~エイムはデバイスから~</b></p>
</div>

<div class="index-main">
  <h1>マウスを表示するページです</h1>

  <div class="mice">
    <ul>マウス一覧
      <% @mice.each do |mouse| %>
        <li>
          <%= link_to  mouse_path(mouse.id) do %>
            <div class="mouse-overview">
              <div class="mouse-image-detail">
                <%= image_tag mouse.image.variant(resize: '300x200'), class:"image_tag" %>
              </div>

              <div class="mouse-name-maker">
                <div class="mouse-name-text">
                  <td><%= mouse.name %></td>
                </div>

                <div class="mouse-maker-text">
                  <td><%= mouse.maker.name %></td>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/mouses/show.html.erb
<%= render 'share/header' %>

<h1> <%=@mouse.name%>  のページ</h1>

<div class="mice">
  <h2>マウス概要</h2>
      <div class="mouse-details">
        <div class="mouse-detail-image">
          <%= image_tag @mouse.image.variant(resize: '300x200'), class:"image_tag" %>
        </div>
        <div class="mouse-info-boxtable">
          <div class="mouse-detail">
            <td>マウスの名前：<%= @mouse.name %></td>
          </div>

          <div class="mouse-detail">
            <td>メーカー名：<%= @mouse.maker.name %></td>
          </div>

          <div class="mouse-detail">
            <td>接続方式：<%= @mouse.connection.name %></td>
          </div>

          <div class="mouse-detail">
            <td>形状：<%= @mouse.symmetry.name %></td>
          </div>

          <div class="mouse-detail">
            <td>重さ：<%= @mouse.weight %>g</td>
          </div>

          <div class="mouse-detail">
            <td>dpi：<%= @mouse.dpi %>dpi</td>
          </div>

          <div class="mouse-detail">
            <td>設定ソフトウェアの有無：<%= @mouse.software.name %></td>
          </div>

          <div class="mouse-detail">
            <td>設定ソフトウェアのURL：<%= @mouse.software_url %></td>
          </div>

          <div class="mouse-detail">
            <td>購入サイトのURL：<%= @mouse.order_url %></td>
          </div>
        </div>
      </div>
</div>

<div class="mouse-editer">
  <% if user_signed_in? && current_user.admin?%>
    <%= link_to '編集する', edit_admin_mouse_path(@mouse.id), method: :get, class: "edit-btn"%>
    <%= link_to '削除する', admin_mouse_path(@mouse.id), method: :delete, class: "delete-btn" %>
  <% end %>
</div>

<div class="review-index">
  <h2><b>マウスレビュー一覧</b></h2>
  <div class="reviews">
    <ul>
      <% @reviews.each do |review|%>
      <li>
        <div class="mouse-posted-review">
          <%= review.user.nickname %>さんのレビュー
        </div>

        <div class="mouse-posted-review">
          <%= review.rating %>点
        </div>

        <% if user_signed_in? && current_user.id == review.user_id%>
          <%= link_to '削除する', review_path(review.id, mouse_id: @mouse.id), method: :delete, class: "delete-btn"%>
        <% end%>

        <div class="mouse-posted-review">
          <div class="weight-bold-text">
          握り方：<%= review.grip_type.name %>
          </div>
        </div>

        <% if review.user.hand_size.present?%>
        <div class="mouse-posted-review">
          手の大きさ：<%= review.user.hand_size %>cm
        </div>
        <% end %>

        <div class="mouse-posted-review">
          <div class="weight-bold-text">
          使用したゲーム：<%= review.play_game.name %>
          </div>
        </div>

        <div class="mouse-posted-review">
          <div class="weight-bold-text">
          感想：
          </div>
          <%= review.usability %>
        </div>
      <li>
      <% end %>
    </ul>
  </div>
</div>

<div class="review-form">
<%if user_signed_in? && current_user.admin == false %>
  <h2><b>マウスレビューの投稿</b></h2>
  <%= form_with model: @review, url: reviews_path, local: true do |f|%>

    <div class="review-summery">
      <div class="weight-bold-text">
        握り方
        <span class="require-text">必須</span>
      </div>
    </div>
    <%= f.collection_select(:grip_type_id, GripType.all, :id, :name, {}, {class:"mouse-grip"}) %>

    <div class="review-summery">
      <div class="weight-bold-text">
        使用したゲーム
        <span class="require-text">必須</span>
      </div>
    </div>
    <%= f.collection_select(:play_game_id, PlayGame.all, :id, :name, {}, {class:"mouse-playgame"}) %>

    <div class="review-summery">
      <div class="weight-bold-text">
        評価（1~5の数字で評価:1が最低、5が最高）
        <span class="require-text">必須</span>
      </div>
    </div>
    <%= f.number_field :rating, min: 1, max: 5 %>

    <div class="review-summery">
      <div class="weight-bold-text">
        使用感
        <span class="require-text">必須</span>
      </div>
    </div>
    <%= f.text_area :usability, placeholder: "使った感想" %>

    <%= f.hidden_field :mouse_id, value: @mouse.id %>

    <div class="send-btn">
    <%= f.submit '投稿する' %>
    </div>
  <% end %>
<% end %>
</div>

app/views/share/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message|%>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/share/_header.html.erb
<header class="page-header">
  <div class='logo' >
  <%= link_to image_tag('mouse-review-logo.png', class:"awd-logo"), root_path %>
  </div>
  
  <div class='login_tag'>
    <div class="mouse-post-btn">
      <% if user_signed_in? && current_user.admin? %>
        <%= link_to 'マウス投稿ページ', new_admin_mouse_path %>
      <% end %>
    </div>

    <div class="sign-in-btn">
      <% if user_signed_in? %>
        <%= "#{current_user.nickname}がログイン中です" %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'ログイン', new_user_session_path %>
        <%= link_to '新規登録',  new_user_registration_path %>
      <% end %>
    </div>
  </div>
</header>